version: '3'
services: 
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: on-failure