version: '3'
services: 
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=postgres
    
  webapp:
    image: 785854/webapp:v1
    ports:
      - "5000"
    restart: on-failure
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - webapp
    ports:
      - "4000:4000"